# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [63]:
# import libraries
import pandas as pd
import numpy as np

#### Import data set.

Read the dataset `pokemon.csv` into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [64]:
# import dataset
pokemon = pd.read_csv('pokemon.csv')
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

#### Print first 10 rows of `pokemon`.

In [65]:
# your code here
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [91]:
# your code here
pokemon[['Type 1', 'Type 2']]
print(pokemon['Type 1'].unique())
print(pokemon['Type 2'].unique())
types1 = pokemon['Type 1'].unique()
types2 = pokemon['Type 2'].unique()

my_list=[]
for item in pokemon['Type 2'].unique():
    if str(item) != 'nan':
        my_list.append(item)
print('my_list is:', my_list)
types2 = my_list

['Grass' 'Fire' 'Water' 'Bug' 'Normal' 'Poison' 'Electric' 'Ground'
 'Fairy' 'Fighting' 'Psychic' 'Rock' 'Ghost' 'Ice' 'Dragon' 'Dark' 'Steel'
 'Flying']
['Poison' nan 'Flying' 'Dragon' 'Ground' 'Fairy' 'Grass' 'Fighting'
 'Psychic' 'Steel' 'Ice' 'Rock' 'Dark' 'Water' 'Electric' 'Fire' 'Ghost'
 'Bug' 'Normal']
my_list is: ['Poison', 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass', 'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water', 'Electric', 'Fire', 'Ghost', 'Bug', 'Normal']

In [92]:
set(types1) == set(types2)

True

In [93]:
types = types1

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [85]:
# your code here
def remove_mega(name):
    if 'Mega' in name:
        name = 'Mega' + name.split('Mega')[1]
    return name
    

print (remove_mega('VenusaurMega Venusaur'))
pokemon['Name'].apply(remove_mega)

# test transformed data
# df.head(10)

Mega Venusaur

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3            Mega Venusaur
4               Charmander
              ...
795                Diancie
796           Mega Diancie
797    HoopaHoopa Confined
798     HoopaHoopa Unbound
799              Volcanion
Name: Name, Length: 800, dtype: object

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [77]:
# your code here
pokemon['A/D Ratio'] = round(pokemon['Attack'] / pokemon['Defense'],1)
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.0
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,1.0
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,1.0
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.8
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.2

#### Identify the pokemon with the highest `A/D Ratio`.

In [80]:
# your code here
pokemon['A/D Ratio'].max()
pokemon[pokemon['A/D Ratio'].max()== pokemon['A/D Ratio']]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.0

#### Identify the pokemon with the lowest A/D Ratio.

In [81]:
# your code here
pokemon[pokemon['A/D Ratio'].min()== pokemon['A/D Ratio']]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.0

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [136]:
# # your code here
def comb_types(row):
    if row['Type 2'] in types:
        return row['Type 1'] + '-' + row['Type 2']
    return row['Type 1']

pokemon['Combo Type'] = pokemon.apply(comb_types, axis=1)
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.0,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,1.0,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,1.0,Grass-Poison
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.8,Grass-Poison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.2,Fire

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [161]:
# your code here
display(pokemon.groupby(['A/D Ratio']).max().reset_index())
max_adr = pokemon.groupby(['A/D Ratio']).max().reset_index()
max_adr.sort_values(by = 'A/D Ratio', ascending=False).head()
# display(pokemon.groupby(['A/D Ratio']).agg(max())
# pokemon['A/D Ratio'].max()
# pokemon[pokemon['A/D Ratio'].max()== pokemon['A/D Ratio']]

/var/folders/rj/ty5_khc929v572g5r_tjk0sw0000gn/T/ipykernel_19328/201941211.py:2: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  display(pokemon.groupby(['A/D Ratio']).max().reset_index())

,A/D Ratio,#,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Combo Type
0,0.0,213,Shuckle,Bug,505,20,10,230,10,230,5,2,False,Bug-Rock
1,0.2,129,Magikarp,Water,200,20,10,55,15,20,80,1,False,Water
2,0.3,703,Togepi,Steel,540,105,52,168,140,150,70,6,False,Steel-Psychic
3,0.4,665,Yamask,Water,600,95,85,200,130,160,90,6,True,Water-Psychic
4,0.5,616,Wynaut,Water,610,103,125,230,130,200,97,5,True,Water-Ice
5,0.6,713,Wobbuffet,Water,630,190,140,230,145,140,104,6,True,Water-Rock
6,0.7,719,Zigzagoon,Water,680,106,110,150,103,154,140,6,True,Water-Rock
7,0.8,718,Zygarde50% Forme,Water,700,150,110,133,175,150,150,6,True,Water-Rock
8,0.9,721,Yanmega,Water,630,165,120,130,165,130,135,6,True,Water-Psychic
9,1.0,702,Wooper,Water,720,255,145,150,150,154,125,6,True,Water-Steel
10,1.1,699,Zapdos,Water,770,130,180,160,150,140,180,6,True,Water-Poison
11,1.2,701,Zweilous,Water,680,150,150,120,154,129,130,6,True,Water-Ground
12,1.3,676,Zubat,Water,700,125,155,120,170,135,120,6,True,Water-Poison
13,1.4,717,Yveltal,Water,680,126,155,110,131,154,135,6,True,Water-Ground
14,1.5,719,Unown,Rock,700,110,170,115,160,110,145,6,True,Rock-Fairy
15,1.6,675,Zorua,Water,670,150,185,115,140,105,150,6,True,Water-Flying
16,1.7,646,Ursaring,Water,770,160,170,100,180,160,115,5,True,Water
17,1.8,720,Zoroark,Psychic,780,150,180,100,180,130,145,6,True,Psychic-Ghost
18,1.9,522,Zangoose,Water,780,110,190,100,154,115,130,5,True,Water
19,2.0,554,Wailord,Water,630,170,160,80,130,80,160,5,False,Water-Dark
20,2.1,620,Shuppet,Psychic,780,135,150,70,194,120,140,5,True,Psychic
21,2.2,567,Whismur,Rock,567,115,165,75,112,110,110,5,False,Rock-Flying
22,2.3,106,Mankey,Fighting,455,50,120,53,35,110,87,1,False,Fighting
23,2.4,430,Honchkrow,Dark,505,100,125,52,105,52,71,4,False,Dark-Flying
24,2.5,566,DarmanitanStandard Mode,Rock,565,105,150,60,115,60,115,5,False,Rock-Flying
25,2.7,720,Pichu,Psychic,680,80,160,60,170,130,80,6,True,Psychic-Dark
26,2.8,409,Rampardos,Rock,495,97,165,60,65,50,58,4,False,Rock
27,3.0,681,Sharpedo,Water,600,70,150,50,150,50,150,6,True,Water-Dark
28,3.1,408,Cranidos,Rock,350,67,125,40,30,30,58,4,False,Rock
29,3.8,15,BeedrillMega Beedrill,Bug,495,65,150,40,15,80,145,1,False,Bug-Poison
30,4.5,318,Carvanha,Water,305,45,90,20,65,20,65,3,False,Water-Dark
31,9.0,386,DeoxysAttack Forme,Psychic,600,50,180,20,180,20,150,3,True,Psychic

/var/folders/rj/ty5_khc929v572g5r_tjk0sw0000gn/T/ipykernel_19328/201941211.py:3: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  max_adr = pokemon.groupby(['A/D Ratio']).max().reset_index()

,A/D Ratio,#,Name,Type 1,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Combo Type
31,9.0,386,DeoxysAttack Forme,Psychic,600,50,180,20,180,20,150,3,True,Psychic
30,4.5,318,Carvanha,Water,305,45,90,20,65,20,65,3,False,Water-Dark
29,3.8,15,BeedrillMega Beedrill,Bug,495,65,150,40,15,80,145,1,False,Bug-Poison
28,3.1,408,Cranidos,Rock,350,67,125,40,30,30,58,4,False,Rock
27,3.0,681,Sharpedo,Water,600,70,150,50,150,50,150,6,True,Water-Dark

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)